version: '3.8'

services:
  api:
    build: .
    container_name: finance-api
    expose:
      - '3000'
    env_file:
      - .env.production
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:latest
    container_name: finance-mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: finance-app
    volumes:
      - mongodb_data:/data/db
    restart: always

  nginx:
    image: nginx:latest
    container_name: finance-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

volumes:
  mongodb_data:
