version: '3.9'

services:
  api:
    build: .
    container_name: api-pigmoney
    expose:
      - '3001:3000'
    env_file:
      - .env.production
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb-pigmoney
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: app-pigmoney
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
