version: '3.9'

services:
  api:
    build: .
    container_name: api-pigmoney
    expose:
      - '3000'           # expose, não precisa mapear porta para fora (nginx cuida disso)
    env_file:
      - .env.production
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb-pigmoney
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: app-pigmoney
    volumes:
      - mongodb_data:/data/db
    restart: always

  nginx:
    image: nginx:latest
    container_name: finance-nginx
    ports:
      - '3001:80' # usa 3001 no ambiente local pra não conflitar com outros nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    restart: always

volumes:
  mongodb_data:
