version: '3.8'

services:
  api:
    build: .
    container_name: finance-api
    ports:
      - '3000:3000'
    env_file:
      - .env.production
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:latest
    container_name: finance-mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: finance-app
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
