version: '3.9'

services:
  api:
    build: .
    container_name: api-pigmoney
    ports:
      - '3000:3000'
    env_file:
      - .env.production
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb-pigmoney
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: app-pigmoney
    volumes:
      - mongodb_data:/data/db
    restart: always

  nginx:
    image: nginx:latest
    container_name: finance-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    restart: always

volumes:
  mongodb_data:
